import fractions
x=fractions.Fraction(1,3)
print(x)
y=fractions.Fraction(6,4)
print(y)
l=fractions.Fraction(1,1)
print(l)
j=fractions.Fraction(10,5)
print(j)
t=fractions.Fraction('1.13')
print(t)
p=fractions.Fraction(1.13)
print(p)
s=fractions.Fraction('8/25')
print(s)
limit=fractions.Fraction('3.4565').limit_denominator(10)
print(limit)
m=fractions.Fraction(113,100)
m2=fractions.Fraction(25,18)
print(m+m2)
print(int(2.99))

